### ISSUE TITLE
Install with AnkiHub: HTTP Error 404

### ISSUE THREAD

**Issue by CNG** [Stvad/CrowdAnki#16] opened 2017-05-10 19:25 UTC
I saw the note [AnkiHub](https://github.com/dayjaby/AnkiHub) can be used with this plugin. Thus I installed AnkiHub and tried to use it to install CrowdAnki. In the "Path" dialog, I entered `Stvad/CrowdAnki`.  The result was this error:

> An error occurred in an add-on.
> Please post on the add-on forum:
> https://anki.tenderapp.com/discussions/add-ons
> 
> Traceback (most recent call last):
>   File "/Users/cgorichanaz/Library/Application Support/Anki2/addons/___ankihub.py", line 271, in addRepository
>     update([repo],install=True)
>   File "/Users/cgorichanaz/Library/Application Support/Anki2/addons/___ankihub.py", line 235, in update
>     response = urllib2.urlopen("https://api.github.com/repos/{0}/releases/tags/{1}".format(path,minorTagName))
>   File "urllib2.pyc", line 127, in urlopen
>   File "urllib2.pyc", line 410, in open
>   File "urllib2.pyc", line 523, in http_response
>   File "urllib2.pyc", line 448, in error
>   File "urllib2.pyc", line 382, in _call_chain
>   File "urllib2.pyc", line 531, in http_error_default
> urllib2.HTTPError: HTTP Error 404: Not Found

I am already hastily trying to wrap up a tangent off a tangent off a tangent of what I am really trying to work on, so instead of tracing this more (maybe I made a simple mistake), I've just installed CrowdAnki via the traditional numeric ID method.

**Comment by dawch** [comment] 2017-05-23 13:13
I can confirm I got the same error trying to install via ankihub. Mac OS X Anki version 2.0.36

**Comment by Stvad** [comment] 2017-05-23 20:42
Hey, sorry about it. I'm currently traveling. I'd be able to look at why it has stopped working in 2-3 weeks.

**Comment by Stvad** [comment] 2017-08-12 13:34
Not sure what is the reason behind this -_-. I don't see any other plugins using AnkiHub mechanism (so I'm not entirely sure that it's still in the operational state), and I did not change a format of my release versions.

**Comment by CNG** [comment] 2017-08-13 16:56
Thanks for looking into it. I am doing fine with this as is... figuring out my general Anki structure and sensible backup strategy is still my main (Anki related) task!

**Comment by Stvad** [comment] 2019-02-23 19:04
Closing this as AnkiHub does not seem to be actively developed anymore :(

**Closed by Stvad** 2019-02-23 19:04 UTC
Labels: bug, help wanted
